### ISSUE TITLE
Plugin sends empty authentication if username is not specified

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-plugin-bells#145]
If the plugin is created with only account and password, the requestCredentials function will send no authentication during the connect function. Passing the username into the plugin parameters appears to fix this.

**Comment by dappelt** [comment]
`ilp-plugin-bells` makes an unauthenticated request to `/accounts/:name` to resolve the username. As just discussed, in your particular scenario the username was not resolved because unauthenticated requests to the endpoint are disallowed.

To fix this, you have two options:
1) Make your ledger compliant with fb-ledger and allow unauthenticated requests to `/accounts/:name`.
2) Pass in the username when instantiating the plugin.

**Comment by sharafian** [comment]
Looks like this was caused by a ledger problem, not a plugin one
